package net.novaproject.novauhc.lang.special;

import net.novaproject.novauhc.lang.Lang;
import java.util.Map;

public enum LegendLang implements Lang {

    CHOOSE_CLASS_WELCOME("§6§l⚔ Legends §r§eVous avez §c%choose_time% minutes §epour choisir vos classes : §a/ld choose","§6§l⚔ Legends §r§eYou have §c%choose_time% minutes §eto choose your class: §a/ld choose"),
    CHOOSE_CLASS_TIME_EXPIRED("§6§l⚔ Legends §r§cLe temps de sélection est terminé !","§6§l⚔ Legends §r§cClass selection time has expired!"),
    CLASS_ALREADY_CHOSEN("§c[Legend] Vous avez déjà une classe.","§c[Legend] You already have a class."),
    CLASS_TAKEN_IN_TEAM("§c[Legend] La classe %legend_name% a déjà été choisie dans votre équipe.","§c[Legend] The class %legend_name% is already taken in your team."),
    CLASS_ASSIGNED_SUCCESS("§a[Legend] Vous avez choisi la classe : §6%legend_name%","§a[Legend] You have chosen the class: §6%legend_name%"),
    CLASS_ASSIGNED_RANDOM("§e[Legend] Classe assignée automatiquement : §6%legend_name%","§e[Legend] Class automatically assigned: §6%legend_name%"),
    NO_TEAM_ERROR("§c[Legend] Vous devez être dans une équipe.","§c[Legend] You must be in a team."),
    UI_CHOOSE_TITLE("§6§lChoisir une Légende §7(%count% disponibles)","§6§lChoose a Legend §7(%count% available)"),
    CMD_SCENARIO_NOT_ACTIVE("§c[Legend] Le scénario UHC Legends doit être actif !","§c[Legend] The UHC Legends scenario must be active!"),
    CMD_CHOOSE_EXPIRED("§c[Legend] Vous ne pouvez plus choisir de classe.","§c[Legend] You can no longer choose a class."),
    CMD_NO_POWER("§c[Legend] Vous n\'avez pas de classe assignée.","§c[Legend] You don\'t have an assigned class."),

    ROLE_DESC_ASSASSIN("§8§m-----------§d L\'Assassin §8§m-----------\n§dPouvoirs :\n§f• Lame Secrète (Fer Sharpness I)\n§f• +%extra_hearts% cœurs supplémentaires\n§f• Force I si Lame Secrète + < 2 épées\n§8§m-------------------------------------","§8§m-----------§d The Assassin §8§m-----------\n§dAbilities:\n§f• Secret Blade (Iron Sharpness I)\n§f• +%extra_hearts% extra hearts\n§f• Strength I with Secret Blade + < 2 swords\n§8§m-----------------------------------------"),
    ROLE_DESC_MAGE("§8§m-----------§d Le Mage §8§m-----------\n§dPouvoirs :\n§f• 3 potions jetables au début\n§f• Régénère 3 potions / 10 minutes\n§f• (Force, Résistance, Vitesse)\n§8§m------------------------------------","§8§m-----------§d The Mage §8§m-----------\n§dAbilities:\n§f• 3 splash potions at start\n§f• Regenerates 3 potions / 10 minutes\n§f• (Strength, Resistance, Speed)\n§8§m--------------------------------------"),
    ROLE_DESC_ARCHER("§8§m-----------§d L\'Archer §8§m-----------\n§dPouvoirs :\n§f• Arc Power II Infinity I\n§f• Dégâts d\'arc augmentés\n§f• 25% chance de Slowness sur flèche\n§8§m-------------------------------------","§8§m-----------§d The Archer §8§m-----------\n§dAbilities:\n§f• Bow Power II Infinity I\n§f• Increased bow damage\n§f• 25% Slowness chance on arrow\n§8§m---------------------------------------"),
    ROLE_DESC_TANK("§8§m-----------§d Le Tank §8§m-----------\n§dPouvoirs :\n§f• +%extra_hearts% cœurs supplémentaires\n§f• Résistance I quand vie faible\n§8§m------------------------------------","§8§m-----------§d The Tank §8§m-----------\n§dAbilities:\n§f• +%extra_hearts% extra hearts\n§f• Resistance I when low health\n§8§m--------------------------------------"),
    ROLE_DESC_NAIN("§8§m-----------§d Le Nain §8§m-----------\n§dPouvoirs :\n§f• Actif : Armure diamant Prot II (30s)\n§f• Cooldown : 10 minutes\n§f• Haste I permanente\n§8§m------------------------------------","§8§m-----------§d The Dwarf §8§m-----------\n§dAbilities:\n§f• Active: Diamond armor Prot II (30s)\n§f• Cooldown: 10 minutes\n§f• Permanent Haste I\n§8§m--------------------------------------"),
    ROLE_DESC_ZEUS("§8§m-----------§d Zeus §8§m-----------\n§dPouvoirs :\n§f• 10% éclair au corps-à-corps\n§f• 20% Speed I 10s au corps-à-corps\n§f• Actif : 2 effets aléatoires (cd 10min)\n§8§m-----------------------------------","§8§m-----------§d Zeus §8§m-----------\n§dAbilities:\n§f• 10% lightning on melee hit\n§f• 20% Speed I 10s on melee hit\n§f• Active: 2 random effects (10min cd)\n§8§m-----------------------------------"),
    ROLE_DESC_NECROMANCIEN("§8§m-------§d Le Nécromancien §8§m-------\n§dPouvoirs :\n§f• Actif : 2 squelettes + 3 baby zombies\n§f• Ciblent l\'ennemi le plus proche (cd 10min)\n§f• Night Vision permanente\n§8§m------------------------------------------","§8§m-------§d The Necromancer §8§m-------\n§dAbilities:\n§f• Active: 2 skeletons + 3 baby zombies\n§f• Target nearest enemy (10min cd)\n§f• Permanent Night Vision\n§8§m-----------------------------------------"),
    ROLE_DESC_SUCCUBE("§8§m-----------§d La Succube §8§m-----------\n§dPouvoirs :\n§f• Vol de vie au corps-à-corps (+1 ♥)\n§f• Actif : Absorption III équipe (cd 6min)\n§8§m-----------------------------------------","§8§m-----------§d The Succubus §8§m-----------\n§dAbilities:\n§f• Lifesteal on melee hit (+1 ♥)\n§f• Active: Absorption III to team (6min cd)\n§8§m-------------------------------------------"),
    ROLE_DESC_SOLDAT("§8§m-----------§d Le Soldat §8§m-----------\n§dPouvoirs :\n§f• Résistance I permanente\n§f• Bonus dégâts épée (corps-à-corps)\n§f• Équipement fer Prot I complet\n§8§m--------------------------------------","§8§m-----------§d The Soldier §8§m-----------\n§dAbilities:\n§f• Permanent Resistance I\n§f• Bonus sword damage (melee)\n§f• Full iron Prot I equipment\n§8§m----------------------------------------"),
    ROLE_DESC_PRINCESSE("§8§m-----------§d La Princesse §8§m-----------\n§dPouvoirs :\n§f• Immunité dégâts de chute\n§f• +%extra_hearts% cœurs supplémentaires\n§f• Speed I permanente\n§8§m------------------------------------------","§8§m-----------§d The Princess §8§m-----------\n§dAbilities:\n§f• Fall damage immunity\n§f• +%extra_hearts% extra hearts\n§f• Permanent Speed I\n§8§m------------------------------------------"),
    ROLE_DESC_CAVALIER("§8§m-----------§d Le Cavalier §8§m-----------\n§dPouvoirs :\n§f• Actif : Cheval Royal (cd 5min)\n§f• Lance Royale (Diamant Sharp I)\n§8§m-----------------------------------------","§8§m-----------§d The Knight §8§m-----------\n§dAbilities:\n§f• Active: Royal Horse (5min cd)\n§f• Royal Lance (Diamond Sharp I)\n§8§m---------------------------------------"),
    ROLE_DESC_OGRE("§8§m-----------§d L\'Ogre §8§m-----------\n§dPouvoirs :\n§f• +%extra_hearts% cœurs supplémentaires\n§f• %start_gapples% gapples au début\n§f• Malus si < 5 gapples (Slow + Weakness)\n§f• Effet aléatoire en mangeant une gapple\n§8§m-------------------------------------","§8§m-----------§d The Ogre §8§m-----------\n§dAbilities:\n§f• +%extra_hearts% extra hearts\n§f• %start_gapples% gapples at start\n§f• Debuff if < 5 gapples (Slow + Weakness)\n§f• Random effect when eating a gapple\n§8§m---------------------------------------"),
    ROLE_DESC_DRAGON("§8§m-----------§d Le Dragon §8§m-----------\n§dPouvoirs :\n§f• Fire Resistance permanente\n§f• 30% chance feu au corps-à-corps\n§f• Actif : Boule de feu (cd 5min)\n§f• +%extra_hearts% cœurs supplémentaires\n§8§m---------------------------------------","§8§m-----------§d The Dragon §8§m-----------\n§dAbilities:\n§f• Permanent Fire Resistance\n§f• 30% ignite on melee hit\n§f• Active: Fireball (5min cd)\n§f• +%extra_hearts% extra hearts\n§8§m----------------------------------------"),
    ROLE_DESC_MEDECIN("§8§m-----------§d Le Médecin §8§m-----------\n§dPouvoirs :\n§f• Zone Régénération I (6 blocs) alliés\n§f• 5 gapples au début\n§f• Régénération I permanente\n§8§m----------------------------------------","§8§m-----------§d The Medic §8§m-----------\n§dAbilities:\n§f• Regen I zone (6 blocks) for allies\n§f• 5 gapples at start\n§f• Permanent Regeneration I\n§8§m--------------------------------------"),
    ROLE_DESC_PRISONNIER("§8§m-----------§d Le Prisonnier §8§m-----------\n§dPouvoirs :\n§f• Speed I permanente\n§f• Actif : Enchaîne ennemi proche\n§f• (Slowness II + Weakness I, cd 5min)\n§8§m-------------------------------------------","§8§m-----------§d The Prisoner §8§m-----------\n§dAbilities:\n§f• Permanent Speed I\n§f• Active: Chain nearest enemy\n§f• (Slowness II + Weakness I, 5min cd)\n§8§m------------------------------------------"),
    ROLE_DESC_CORNE("§8§m-----------§d La Corne §8§m-----------\n§dPouvoirs :\n§f• Weakness I permanente (malus)\n§f• 4 Mélodies (buff équipe 30 blocs) :\n§e  ♪ Feu : Fire Res II 12s (cd 1min)\n§a  ♪ Heal : Full heal (cd 10min)\n§9  ♪ Metal : Résist II 5s (cd 1min)\n§b  ♪ Air : Speed II 8s (cd 3min)\n§8§m---------------------------------------","§8§m-----------§d The Horn §8§m-----------\n§dAbilities:\n§f• Permanent Weakness I (debuff)\n§f• 4 Melodies (team buff 30 blocks):\n§e  ♪ Fire: Fire Res II 12s (1min cd)\n§a  ♪ Heal: Full heal (10min cd)\n§9  ♪ Metal: Resist II 5s (1min cd)\n§b  ♪ Air: Speed II 8s (3min cd)\n§8§m--------------------------------------"),
    ROLE_DESC_MARIONNETTISTE("§8§m-------§d Le Marionnettiste §8§m-------\n§dPouvoirs :\n§f• Kill = victime devient marionnette\n§f• Rejoint votre équipe (type aléatoire) :\n§c  → Féroce (Force I)\n§9  → Massif (Résistance I)\n§b  → Timide (Speed I)\n§f• Poison si > 16 blocs\n§f• Marionnettes meurent si vous mourez\n§8§m-----------------------------------------","§8§m-------§d The Puppeteer §8§m-------\n§dAbilities:\n§f• Kill = victim becomes puppet\n§f• Joins your team (random type):\n§c  → Fierce (Strength I)\n§9  → Massive (Resistance I)\n§b  → Shy (Speed I)\n§f• Poison if > 16 blocks away\n§f• Puppets die if you die\n§8§m--------------------------------------"),
    ROLE_DESC_PALADIN("§8§m-----------§d Le Paladin §8§m-----------\n§dPouvoirs :\n§f• +%extra_hearts% cœurs supplémentaires\n§f• Résistance I quand vie faible\n§f• Force I si allié proche (8 blocs)\n§f• Actif : Bénédiction (cd 8min)\n§f• Épée Sacrée (Or Sharp II)\n§8§m----------------------------------------","§8§m-----------§d The Paladin §8§m-----------\n§dAbilities:\n§f• +%extra_hearts% extra hearts\n§f• Resistance I when low health\n§f• Strength I when ally nearby (8 blocks)\n§f• Active: Blessing (8min cd)\n§f• Sacred Sword (Gold Sharp II)\n§8§m------------------------------------------"),

    ;

    private final Map<String, String> translations;

    LegendLang(String fr, String en) {
        this.translations = Map.of("fr_FR", fr, "en_US", en);
    }

    @Override public String getKey() { return "legend." + name(); }
    @Override public Map<String, String> getTranslations() { return translations; }
}
